version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c09f61d6f
      POSTGRES_DB: postgres
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flask_container
    restart: always
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:c09f61d6f@db:5432/postgres
    ports:
      - "5000:5000"
